services:
  - type: web
    name: minecraft-email-verifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: worker
    name: email-cron-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
